# Change these first
owner: dhalldog # Your GitHub organization or username, where this repository lives
repo: WCSD-Service-Status-Pages # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Apple
    url: https://www.apple.com/
  - name: Canvas
    url: https://www.instructure.com/
  - name: Jamf Pro
    url: https://waukeecommsd.jamfcloud.com/
  - name: Mosyle
    url: https://myschool.mosyle.com/#
  - name: Clever
    url: https://www.clever.com/
  - name: Minga
    url: https://status.minga.io/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /WCSD-Service-Status-Pages
  logoUrl: https://github.com/dhalldog/WCSD-Service-Status-Pages/blob/master/assets/WCSD.svg
  name: "Waukee Community School District"
  introTitle: "Status Page for curriculum services"
  introMessage: Scroll through the list to find the service you are experiencing issues with to see if the website is down currently. If you continue experiencing issues with the website make sure to contact your IT department at ticket@waukeeschools.org!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Tickets
      href: https://ticket.waukeeschools.org/tickets/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
