# Change these first
owner: dhalldog # Your GitHub organization or username, where this repository lives
repo: WCSD-Service-Status-Pages # The name of this repository

sites:
  - name: Amazon(AWS)
    url: https://aws.amazon.com/
  - name: Apple
    url: https://www.apple.com/
  - name: Apple School Manager
    url: https://school.apple.com/#/main/users
  - name: Canvas
    url: https://www.instructure.com/
  - name: Claris Connect
    url: https://connect.claris.com/login
  - name: Class Kick
    url: https://classkick.com/
  - name: Clever
    url: https://www.clever.com/
  - name: Cloud Flare
    url: https://www.cloudflare.com/
  - name: Frontline
    url: https://app.frontlineeducation.com/
  - name: Google
    url: https://www.google.com
  - name: Jamf Pro
    url: https://waukeecommsd.jamfcloud.com/
  - name: Khan Academy
    url: https://www.khanacademy.org/
  - name: Learning Ally
    url: https://learningally.org/
  - name: MackinVIA
    url: https://mackinvia.com/
  - name: McGraw Hill
    url: https://www.mheducation.com/ 
  - name: Minga
    url: https://status.minga.io/
  - name: Mosyle
    url: https://myschool.mosyle.com/
  - name: NIM
    url: https://www.tools4ever.com/nim/
  - name: OKTA
    url: https://waukeeschools.okta.com/
  - name: Pearson
    url: https://www.pearson.com/
  - name: PowerSchool
    url: https://waukee.powerschool.com/public/ 
  - name: Savvas
    url: https://www.savvas.com/
  - name: WCSD Tickets
    url: https://ticket.waukeeschools.org/staff/tickets/
  - name: WCSD Website
    url: https://www.waukeeschools.org/
  - name: Visitor Aware
    url: https://status.singlewire.com/
  - name: YouTube
    url: https://www.youtube.com/
    
    


status-website:
  workflowSchedule:
    uptime: "*/5 * * * *"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /WCSD-Service-Status-Pages
  logoUrl: https://raw.githubusercontent.com/dhalldog/WCSD-Service-Status-Pages/refs/heads/master/assets/WCSD.svg
  themeUrl: https://github.com/dhalldog/WCSD-Service-Status-Pages/blob/master/assets/WCSD-Color.css
  name: "Waukee Community School District"
  introTitle: "Status Page for curriculum services"
  introMessage: Scroll through the list to find the service you are experiencing issues with to see if the website is down currently. If you continue experiencing issues with the website make sure to contact your IT department at ticket@waukeeschools.org!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Tickets
      href: https://ticket.waukeeschools.org/tickets/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
